# Generated by Django 4.0.2 on 2022-03-28 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furnix', '0003_product_category_product_sub_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='ecomers/img'),
        ),
    ]
