# Generated by Django 4.0.2 on 2022-05-20 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furnix', '0007_alter_order_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
