# Generated by Django 4.0.2 on 2022-05-20 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furnix', '0008_order_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Availability',
            field=models.CharField(choices=[('In Stock', 'In Stock'), ('Out of Stock', 'Out of Stock')], max_length=100, null=True),
        ),
    ]
