# Generated by Django 4.0.2 on 2022-05-21 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furnix', '0009_product_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='details',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
