# Generated by Django 4.0.2 on 2022-05-21 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('furnix', '0010_product_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='details',
        ),
    ]
